@extends('layouts.master')

@section('content')
    <div class="container">
        <p>
            Terms of Service

    1. Your Acceptance

    BY USING AND/OR VISITING THIS WEBSITE (collectively, including all Content available through the Truyentranh8.me domain name, the "Truyentranh8 Website", or "Website"), YOU SIGNIFY YOUR ASSENT TO TERMS OF USE, WHICH ARE PUBLISHED AT http://Truyentranh8.me/terms.htm AND WHICH ARE INCORPORATED HEREIN BY REFERENCE. If you do not agree to any of these terms, then please do not use the Truyentranh8 Website.

    2. Truyentranh8 Website

    These Terms of Use apply to all users of the Truyentranh8 Website, including users who are also contributors of manga content, information, and other materials or services on the Website. The Truyentranh8 Website may contain links to third party websites that are not owned or controlled by Truyentranh8. Truyentranh8 has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third party websites. In addition, Truyentranh8 will not and cannot censor or edit the content of any third-party site. By using the Website, you expressly relieve Truyentranh8 from any and all liability arising from your use of any third-party website. Accordingly, we encourage you to be aware when you leave the Truyentranh8 Website and to read the terms and conditions and privacy policy of each other website that you visit.

    3. Website Access

    A. Truyentranh8 hereby grants you permission to use the Website as set forth in this Terms of Use, provided that: (i) your use of the Website as permitted is solely for your personal, noncommercial use; (ii) you will not copy or distribute any part of the Website in any medium without Truyentranh8's prior written authorization; (iii) you will not alter or modify any part of the Website other than as may be reasonably necessary to use the Website for its intended purpose; and (iv) you will otherwise comply with the terms and conditions of these Terms of Use.

    B. In order to access some features of the Website, you will have to create an account. You may never use another's account without permission. When creating your account, you must provide accurate and complete information. You are solely responsible for the activity that occurs on your account, and you must keep your account password secure. You must notify Truyentranh8 immediately of any breach of security or unauthorized use of your account. Although Truyentranh8 will not be liable for your losses caused by any unauthorized use of your account, you may be liable for the losses of Truyentranh8 or others due to such unauthorized use.

    C. You agree not to use or launch any automated system, including without limitation, "robots," "spiders," "offline readers," etc., that accesses the Website in a manner that sends more request messages to the Truyentranh8 servers in a given period of time than a human can reasonably produce in the same period by using a convention on-line web browser. Notwithstanding the foregoing, Truyentranh8 grants the operators of public search engines permission to use spiders to copy materials from the site for the sole purpose of creating publicly available searchable indices of the materials, but not caches or archives of such materials. Truyentranh8 reserves the right to revoke these exceptions either generally or in specific cases. You agree not to collect or harvest any personally identifiable information, including account names, from the Website, nor to use the communication systems provided by the Website for any commercial solicitation purposes. You agree not to solicit, for commercial purposes, any users of the Website with respect to their User Submissions.

    4. Intellectual Property Rights

    The content on the Truyentranh8 Website, except all User Submissions (as defined below), including without limitation, the text, software, scripts, graphics, photos, sounds, music, videos, interactive features and the like ("Content") and the trademarks, service marks and logos contained therein ("Marks"), are owned by or licensed to Truyentranh8, subject to copyright and other intellectual property rights under United States and foreign laws and international conventions. Content on the Website is provided to you AS IS for your information and personal use only and may not be used, copied, reproduced, distributed, transmitted, broadcast, displayed, sold, licensed, or otherwise exploited for any other purposes whatsoever without the prior written consent of the respective owners. Truyentranh8 reserves all rights not expressly granted in and to the Website and the Content. You agree to not engage in the use, copying, or distribution of any of the Content other than expressly permitted herein, including any use, copying, ordistribution of User Submissions of third parties obtained through the Website for any commercial purposes. If you download or print a copy of the Content for personal use, you must retain all copyright and other proprietary notices contained therein. You agree not to circumvent, disable or otherwise interfere with security related features of the Truyentranh8 Website or features that prevent or restrict use or copying of any Content or enforce limitations on use of the Truyentranh8 Website or the Content therein.
    5. User Submissions

    A. The Truyentranh8 Website may now or in the future permit the submission of manga or other communications submitted by you and other users ("User Submissions") and the hosting, sharing, and/or publishing of such User Submissions. You understand that whether or not such User Submissions are published, Truyentranh8 does not guarantee any confidentiality with respect to any submissions.
    B. You shall be solely responsible for your own User Submissions and the consequences of posting or publishing them. In connection with User Submissions, you affirm, represent, and/or warrant that: (i) you own or have the necessary licenses, rights, consents, and permissions to use and authorize Truyentranh8 to use all patent, trademark, trade secret, copyright or other proprietary rights in and to any and all User Submissions to enable inclusion and use of the User Submissions in the manner contemplated by the Website and these Terms of Use; and (ii) you have the written consent, release, and/or permission of each and every identifiable individual person in the User Submission to use the name or likeness of each and every such identifiable individual person to enable inclusion and use of the User Submissions in the manner contemplated by the Website and these Terms of Use. For clarity, you retain all of your ownership rights in your User Submissions. However, by submitting the User Submissions to Truyentranh8, you hereby grant Truyentranh8 a worldwide, non-exclusive, royalty-free, sublicenseable and transferable license to use, reproduce, distribute, prepare derivative works of, display, and perform the User Submissions in connection with the Truyentranh8 Website and Truyentranh8's (and its successor's) business, including without limitation for promoting and redistributing part or all of the Truyentranh8 Website (and derivative works thereof) in any media formats and through any media channels. You also hereby grant each user of the Truyentranh8 Website a non-exclusive license to access your User Submissions through the Website, and to use, reproduce, distribute, prepare derivative works of, display and perform such User Submissions as permitted through the functionality of the Website and under these Terms of Use. The foregoing license granted by you terminates once you remove or delete a User Submission from the Truyentranh8 Website.

    C. In connection with User Submissions, you further agree that you will not: (i) submit material that is copyrighted, protected by trade secret or otherwise subject to third party proprietary rights, including privacy and publicity rights, unless you are the owner of such rights or have permission from their rightful owner to post the material and to grant Truyentranh8 all of the license rights granted herein; (ii) publish falsehoods or misrepresentations that could damage Truyentranh8 or any third party; (iii) submit material that is unlawful, obscene, defamatory, libelous, threatening, pornographic, harassing, hateful, racially or ethnically offensive, or encourages conduct that would be considered a criminal offense, give rise to civil liability, violate any law, or is otherwise inappropriate; (iv) post advertisements or solicitations of business: (v) impersonate another person. Truyentranh8 does not endorse any User Submission or any opinion, recommendation, or advice expressed therein, and Truyentranh8 expressly disclaims any and all liability in connection with User Submissions. Truyentranh8 does not permit copyright infringing activities and infringement of intellectual property rights on its Website, and Truyentranh8 will remove all Content and User Submissions if properly notified that such Content or User Submission infringes on another's intellectual property rights. Truyentranh8 reserves the right to remove Content and User Submissions without prior notice. Truyentranh8 will also terminate a User's access to its Website, if they are determined to be a repeat infringer. A repeat infringer is a User who has been notified of infringing activity more than twice and/or has had a User Submission removed from the Website more than twice. Truyentranh8 also reserves the right to decide whether Content or a User Submission is appropriate and complies with these Terms of Service for violations other than copyright infringement and violations of intellectual property law, such as, but not limited to, pornography, obscene or defamatory material, or excessive length. Truyentranh8 may remove such User Submissions and/or terminate a User's access for uploading such material in violation of these Terms of Use at any time, without prior notice and at its sole discretion.

    D. In particular, if you are a copyright owner or an agent thereof and believe that any User Submission or other content infringes upon your copyrights, you may submit a notification pursuant to the Digital Millennium Copyright Act ("DMCA") by providing our Copyright Agent with the following information in writing (see 17 U.S.C 512(c)(3) for further detail):

    (i) A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed;

    (ii) Identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works at a single online site are covered by a single notification, a representative list of such works at that site;

    (iii) Identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled and information reasonably sufficient to permit the service provider to locate the material;

    (iv) Information reasonably sufficient to permit the service provider to contact you, such as an address, telephone number, and, if available, an electronic mail;

    (v) A statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and

    (vi) A statement that the information in the notification is accurate, and under penalty of perjury, that you are authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.

            Truyentranh8's designated Copyright Agent to receive notifications of claimed infringement is: <a href="mailto:contact.Truyentranh8@gmail.com">contact.Truyentranh8@gmail.com</a>. For clarity, only DMCA notices should go to the Copyright Agent; any other feedback, comments, requests for technical support, and other communications should be directed to Truyentranh8 customer service. You acknowledge that if you fail to comply with all of the requirements of this Section 5(D), your DMCA notice may not be valid.
    E. You understand that when using the Truyentranh8 Website, you will be exposed to User Submissions from a variety of sources, and that Truyentranh8 is not responsible for the accuracy, usefulness, safety, or intellectual property rights of or relating to such User Submissions. You further understand and acknowledge that you may be exposed to User Submissions that are inaccurate, offensive, indecent, or objectionable, and you agree to waive, and hereby do waive, any legal or equitable rights or remedies you have or may have against Truyentranh8 with respect thereto, and agree to indemnify and hold Truyentranh8, its Owners/Operators, affiliates, and/or licensors, harmless to the fullest extent allowed by law regarding all matters related to your use of the site.

    F. Truyentranh8 permits you to link to materials on the Website for personal, non-commercial purposes only. Truyentranh8 reserves the right to discontinue any aspect of the Truyentranh8 Website at any time.

    6. Warranty Disclaimer

    YOU AGREE THAT YOUR USE OF THE Truyentranh8 WEBSITE SHALL BE AT YOUR SOLE RISK. TO THE FULLEST EXTENT PERMITTED BY LAW, Truyentranh8, ITS OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, IN CONNECTION WITH THE WEBSITE AND YOUR USE THEREOF. Truyentranh8 MAKES NO WARRANTIES OR REPRESENTATIONS ABOUT THE ACCURACY OR COMPLETENESS OF THIS SITE'S CONTENT OR THE CONTENT OF ANY SITES LINKED TO THIS SITE AND ASSUMES NO LIABILITY OR RESPONSIBILITY FOR ANY (I) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT, (II) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF OUR WEBSITE, (III) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, (IV) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM OUR WEBSITE, (IV) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE WHICH MAY BE TRANSMITTED TO OR THROUGH OUR WEBSITE BY ANY THIRD PARTY, AND/OR (V) ANY ERRORS OR OMISSIONSIN ANY CONTENT OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE Truyentranh8 WEBSITE. Truyentranh8 DOES NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR ANY PRODUCT OR SERVICE ADVERTISED OR OFFERED BY A THIRD PARTY THROUGH THE Truyentranh8 WEBSITE OR ANY HYPERLINKED WEBSITE OR FEATURED IN ANY BANNER OR OTHER ADVERTISING, AND Truyentranh8 WILL NOT BE A PARTY TO OR IN ANY WAY BE RESPONSIBLE FOR MONITORING ANY TRANSACTION BETWEEN YOU AND THIRD-PARTY PROVIDERS OF PRODUCTS OR SERVICES. AS WITH THE PURCHASE OF A PRODUCT OR SERVICE THROUGH ANY MEDIUM OR IN ANY ENVIRONMENT, YOU SHOULD USE YOUR BEST JUDGMENT AND EXERCISE CAUTION WHERE APPROPRIATE.

    7. Limitation of Liability

    IN NO EVENT SHALL Truyentranh8, ITS OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS, BE LIABLE TO YOU FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES WHATSOEVER RESULTING FROM ANY (I) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT, (II) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF OUR WEBSITE, (III) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, (IV) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM OUR WEBSITE, (IV) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE, WHICH MAY BE TRANSMITTED TO OR THROUGH OUR WEBSITE BY ANY THIRD PARTY, AND/OR (V) ANY ERRORS OR OMISSIONS IN ANY CONTENT OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF YOUR USE OF ANY CONTENT POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE Truyentranh8 WEBSITE, WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL THEORY, AND WHETHER ORNOT THE COMPANY IS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THE FOREGOING LIMITATION OF LIABILITY SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW IN THE APPLICABLE JURISDICTION.

    YOU SPECIFICALLY ACKNOWLEDGE THAT Truyentranh8 SHALL NOT BE LIABLE FOR USER SUBMISSIONS OR THE DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF ANY THIRD PARTY AND THAT THE RISK OF HARM OR DAMAGE FROM THE FOREGOING RESTS ENTIRELY WITH YOU.

    8. Indemnity

    You agree to defend, indemnify and hold harmless Truyentranh8, its parent corporation, officers, directors, employees and agents, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney's fees) arising from: (i) your use of and access to the Truyentranh8 Website; (ii) your violation of any term of these Terms of Use; (iii) your violation of any third party right, including without limitation any copyright, property, or privacy right; or (iv) any claim that one of your User Submissions caused damage to a third party. This defense and indemnification obligation will survive these Terms of Service and your use of the Truyentranh8 Website.
    9. Ability to Accept Terms of Use

    You affirm that you are either more than 18 years of age, or an emancipated minor, or possess legal parental or guardian consent, and are fully able and competent to enter into the terms, conditions, obligations, affirmations, representations, and warranties set forth in these Terms of Service, and to abide by and comply with these Terms of Service. In any case, you affirm that you are over the age of 13, as the Truyentranh8 Website is not intended for children under 13. If you are under 13 years of age, then please do not use the Truyentranh8 Website-there are lots of other great web sites for you. Talk to your parents about what sites are appropriate for you.
    10. Assignment

    These Terms of Use, and any rights and licenses granted hereunder, may not be transferred or assigned by you, but may be assigned by Truyentranh8 without restriction.
        </p>
    </div>

    @endsection